### ISSUE TITLE
Alpine环境导入失败

### ISSUE THREAD

**Issue by lingfeng126** [GmSSL/GmSSL-Python#23]
安装[Gmssl](https://github.com/guanzhi/GmSSL)和本python包后尝试导入报错
```
>>> import gmssl
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.11/site-packages/gmssl.py", line 17, in <module>
raise ValueError('Install GmSSL dynamic library from https://github.com/guanzhi/GmSSL')
ValueError: Install GmSSL dynamic library from https://github.com/guanzhi/GmSSL
```

**Comment by lingfeng126** [comment]
find_library("gmssl") 找不到动态库, 怀疑是alpine环境不存在ld, ldconfig等命令导致. [Python文档说明](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries)

**Comment by ferstar** [comment]
@lingfeng126 我提了个 PR #26 完全解决依赖问题了，二进制包见：https://github.com/ferstar/GmSSL-Python/releases/tag/v2.2.2

<img width="1283" height="761" alt="Image" src="https://github.com/user-attachments/assets/aa30aab0-4680-4ce4-b744-4cde31fe10cc" />
